# Generated by Django 4.1.6 on 2023-03-10 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('sadness', models.FloatField(default=0.16666666666666666)),
                ('joy', models.FloatField(default=0.16666666666666666)),
                ('surpise', models.FloatField(default=0.16666666666666666)),
                ('love', models.FloatField(default=0.16666666666666666)),
                ('anger', models.FloatField(default=0.16666666666666666)),
                ('fear', models.FloatField(default=0.16666666666666666)),
                ('text', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
