# Generated by Django 4.1.6 on 2023-05-05 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0003_alter_profile_music'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=10, null=True)),
                ('last_name', models.CharField(max_length=10, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('contact', models.CharField(max_length=15, null=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('age', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileMood',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('happy_songs', models.FloatField(default=3)),
                ('sad_songs', models.FloatField(default=2)),
                ('calm_songs', models.FloatField(default=2)),
                ('energetic_songs', models.FloatField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileEntries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sadness', models.FloatField(default=16.666666666666668)),
                ('joy', models.FloatField(default=16.666666666666668)),
                ('surpise', models.FloatField(default=16.666666666666668)),
                ('love', models.FloatField(default=16.666666666666668)),
                ('anger', models.FloatField(default=16.666666666666668)),
                ('fear', models.FloatField(default=16.666666666666668)),
                ('text', models.CharField(blank=True, max_length=1000, null=True)),
                ('submitted_at', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
