# Generated by Django 4.1.6 on 2023-05-05 19:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0004_customprofile_profilemood_profileentries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileentries',
            name='user',
        ),
        migrations.AddField(
            model_name='profileentries',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
